### ISSUE TITLE
Need UserDashboard 

### ISSUE THREAD

**Issue by MeetPatelLearning** [MeetPatelLearning/TravelYaari-React-Project-For-Contribution#2]
Need UserDashboard with functionalities like :

- history
- Authenticated
- PurchaseHistory
- userInfo etc

**Comment by tanmaytm29** [comment]
I have made the UserDashBoard and made changes.

**Comment by MeetPatelLearning** [comment]
your code has been succesfully merged. thank you for your contribution.

**Comment by tanmaytm29** [comment]
Thank You .Hope to contribute more in future..
